updated view-jwt.sh and rar2zip

diff --git a/bin/rar2zip b/bin/rar2zip
--- a/bin/rar2zip
+++ b/bin/rar2zip
@@ -7,9 +7,20 @@ echo >&2 "Converting RAR to ZIP"
 
 set -ex
 
-IFS="␜"
+USE_SUBDIRS=false
+PREFIX=""
 
-OLDFILE=$(realpath "$1")
+for arg in "$@"; do
+    case "$arg" in
+        --subdir|--subdirs) USE_SUBDIRS=true ;;
+        --prefix=*) PREFIX=${arg##--prefix=} ;;
+        *) OLDFILE="$(realpath "$arg")" ;;
+    esac
+done
+if [[ -z "$OLDFILE" ]]; then
+    echo >&2 "missing filename"
+    exit 1
+fi
 
 # Use RAM disk for temporary files.
 WORKDIR="/dev/shm/"
@@ -31,19 +42,11 @@ function findDepth1 {
     find . -mindepth 1 -maxdepth 1 "$@"
 }
 
-# Find all the .rar files in the specified directory.
-# Using -iname means it will find .rar .RAR .RaR etc.
-# "-printf "%p␜" will cause the file names to be separated by the ␜ symbol,
-# rather than the default newline.
-
 # Get the file name without the extension
-BASENAME=`basename "${OLDFILE%.*}"`
+BASENAME=$(basename "${OLDFILE%.*}")
 
 # Path for the file. The ".zip" file will be moved there.
-DIRNAME=`dirname $OLDFILE`
-
-# Name of the .zip file
-NEWNAME="$BASENAME.zip"
+DIRNAME=$(dirname "$OLDFILE")
 
 # Create a temporary folder for unRARed files
 echo >&2 "Extracting $OLDFILE"
@@ -51,27 +54,32 @@ mkdir "$BASENAME"
 7z x "$OLDFILE" -O"$BASENAME"
 cd "$BASENAME"
 
-if [[ "$2" == "--subdir" ]] ; then
-    echo >&2 "descending 1 subdirectory"
-    # assert only one subdirectory
-    COUNTFILES=$(findDepth1 -print0 | tr -dc '\0'| wc -c)
-    COUNTDIRS=$(findDepth1 -type d -print0 | tr -dc '\0'| wc -c)
-    if [[ "$COUNTFILES" != 1 || "$COUNTDIRS" != 1 ]] ; then
-       echo >&2 "not exactly 1 subdirectory found, exiting"
-       exit 1
-    fi
-    SUBDIR=$(findDepth1 -type d)
+function createNewZip {
+    local NEWNAME="$1"
+    # Zip the files with maximum compression
+    7z a -tzip -mx=9 "$NEWNAME" *
+    # Alternative. MUCH SLOWER, but better compression
+    # 7z a -mm=Deflate -mfb=258 -mpass=15 -r "$NEWNAME" *
 
-    cd "$SUBDIR"
+    # Move the new .zip to the directory containing the original ".rar" file
+    mv "$NEWNAME" "${DIRNAME}/${PREFIX}${NEWNAME}"
+}
+
+if [[ "${USE_SUBDIRS}" == "true" ]] ; then
+    echo >&2 "creating zip for each subdirectory"
+    OLDIFS="$IFS"
+    IFS=$'\n'
+    SUBDIRS=($(findDepth1 -type d -printf "%f\n"))
+    for SUBDIR in "${SUBDIRS[@]}"; do
+        (
+            cd "$SUBDIR"
+            createNewZip "${SUBDIR}.zip"
+        )
+    done
+    IFS="$OLDIFS"
+else
+    createNewZip "${BASENAME}.zip"
 fi
-
-# Zip the files with maximum compression
-7z a -tzip -mx=9 "$NEWNAME" *
-# Alternative. MUCH SLOWER, but better compression
-# 7z a -mm=Deflate -mfb=258 -mpass=15 -r "$NEWNAME" *
-
-# Move the new .zip to the directory containing the original ".rar" file
-mv "$NEWNAME" "${DIRNAME}/${NEWNAME}"
 
 # Delete the temporary directory
 cd $WORKDIR
